### ISSUE TITLE
RdfJSONParser: Disable Date Parsing in Newtonsoft.JSON parser

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#130]
The RdfJsonParser class does not properly handle the case of a literal string that is formatted as an ISO 8601 date/time string. This code:

```c#
using VDS.RDF;
 using VDS.RDF.Parsing;
 ...
 var jsonstr = @"
 {
  ""http://example.com"": {
    ""http://purl.org/dc/terms/issued"": [{
        ""datatype"": ""http://www.w3.org/2001/XMLSchema#date"",
        ""type"": ""literal"",
        ""value"": ""2017-10-24T15:01:53+02:00""
      }]
    }
  }";

  IGraph g = new Graph();
  g.LoadFromString(str1, new RdfJsonParser());
```

Leads to the following exception:
```
Exception has occurred: CLR/VDS.RDF.Parsing.RdfParseException
Exception thrown: 'VDS.RDF.Parsing.RdfParseException' in dotNetRDF.dll: '[Line 4 Column 40 to Line 7 Column 44] Unexpected Token 'Date' encountered, expected a Property Value describing one of the properties of an Object Node'
   at VDS.RDF.Parsing.RdfJsonParser.Error(JsonParserContext context, String message, PositionInfo startPos)
   at VDS.RDF.Parsing.RdfJsonParser.ParseObject(JsonParserContext context, INode subj, INode pred)
   at VDS.RDF.Parsing.RdfJsonParser.ParseObjectList(JsonParserContext context, INode subj, INode pred)
   at VDS.RDF.Parsing.RdfJsonParser.ParsePredicateObjectList(JsonParserContext context, INode subj)
   at VDS.RDF.Parsing.RdfJsonParser.ParseTriples(JsonParserContext context)
   at VDS.RDF.Parsing.RdfJsonParser.ParseGraphObject(JsonParserContext context)
   at VDS.RDF.Parsing.RdfJsonParser.Parse(IRdfHandler handler, TextReader input)
   at VDS.RDF.Parsing.RdfJsonParser.Load(IRdfHandler handler, TextReader input)
   at VDS.RDF.Parsing.StringParser.Parse(IGraph g, String data, IRdfReader reader)
```

This appears to be because the underlying Newtonsoft.JSON parser has converted the ISO 8601 date string in the `value` property into a C# `Date` object, and our RdfJsonParser only expects string values.

This behaviour of the Newstonsoft parser can be disabled via the `DateParseHandling` property on the parser (by setting the property value to `DateParseHandling.None`).

Originally reported via [this SO question](https://stackoverflow.com/questions/47045815/triple-with-iso8601-date-breaks-rdfjson-parser-in-dotnetrdf)

**Comment by pkanavos** [comment]
Perhaps the easiest way to do this would be to set 

    DateParseHandling= DateParseHandling.None;

in CommentIgnoringJsonTextReader's constructors
