### ISSUE TITLE
[Question] How does a PersistentTripleStore relates to a StardogConnector?

### ISSUE THREAD

**Issue by charbull** [dotnetrdf/dotnetrdf#172]
Hello,

I am trying to understand the following so I can resolve the issue in [1](https://github.com/MakoLab/RomanticWeb/issues/68)

I am using StardogConnector as a persistent store. 
I would like to understand how does a PersistentTripleStore relates to a StardogConnector?

Thank you

**Comment by kal** [comment]
The `StardogConnector` implements the `IStorageProvider` interface that is used by `PersistentTripleStore` to read/write graphs (actually indirectly so because the `PersistentTripleStore` wraps the `IStorageProvider` in a `PersistentGraphCollection`). The underlying storage provider is accessible via the `UnderlyingStore` property of the `PersistentTripleStore`.

For query, this is delegated through to the `IStorageProvider` if the implementation also implements `IQueryableStorage` (which in this case the `StardogConnector` does).

As I understand it from the linked issue, you want to find a way to use the reasoning on query. The correct way to test for this would be to check if the underlying storage provider implements the `IReasoningQueryableStorage` interface, if so then you have access to the methods of that interface.

**Comment by charbull** [comment]
@kal thank you very much ! This is helpful !

**Comment by charbull** [comment]
We were able to patch the inference [1](https://github.com/BuildingsLabs/RomanticWeb/blob/develop/RomanticWeb.dotNetRDF/PersistentTripleStoreSparqlCommandExecutionStrategy.cs) from the issue in [2](https://github.com/MakoLab/RomanticWeb/issues/68) but for some reason, we are hitting an timeout exception.

If you have any thoughts on this it would be great,
Thank you

VDS.RDF.Query.RdfQueryException : A HTTP error  occurred while querying the Store.
No response, see aforementioned status line or inner exception for further details
  ----> System.Net.WebException : The operation has timed out
   at VDS.RDF.Storage.BaseStardogConnector.Query(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, String sparqlQuery, Boolean reasoning)
   at VDS.RDF.Storage.BaseStardogConnector.Query(String sparqlQuery, Boolean reasoning)
   at RomanticWeb.DotNetRDF.PersistentTripleStoreSparqlCommandExecutionStrategy.ExecuteSelect(IQuery sparqlQuery, SparqlQueryVariables& variables) in C:\Users\SESA180908\Documents\GitHub\RomanticWeb\RomanticWeb.dotNetRDF\PersistentTripleStoreSparqlCommandExecutionStrategy.cs:line 91
   at RomanticWeb.DotNetRDF.TripleStoreAdapter.ExecuteScalarQuery(IQuery queryModel) in C:\Users\SESA180908\Documents\GitHub\RomanticWeb\RomanticWeb.dotNetRDF\TripleStoreAdapter.cs:line 123
   at RomanticWeb.Linq.EntityQueryExecutor.ExecuteScalar[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedScalarValueInfo.ExecuteScalarQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedScalarValueInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Wpa.Rdf.RomanticWeb.ContextFactoryHelper.ValidateContextFactory(String providerName, EntityContextFactory entityContextFactory)
   at Wpa.Rdf.RomanticWeb.ContextFactoryHelper.CreateFactoryAndAddToCache(String providerName, String nameSpace)
   at Wpa.Rdf.RomanticWeb.ContextFactoryHelper.CreateContext(String providerName, String nameSpace)
   at Wpa.Rdf.RomanticWeb.RdfContext..ctor(String providerName, String nameSpace)
   at Wpa.Rdf.Test.TestHelpers.CreateTestContext(String providerName)
   at Wpa.Rdf.Test.TestHelpers.CreateDataLoader(String providerName)
   at Wpa.Rdf.Test.WpaFixture.Can_create_city(String cityName, String stateName, String countryName)
--WebException
   at System.Net.HttpWebRequest.GetResponse()
   at VDS.RDF.Storage.BaseStardogConnector.Query(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, String sparqlQuery, Boolean reasoning)

**Comment by kal** [comment]
Sorry for the late reply. I missed the reopening of this ticket.

It looks like you have just hit a timeout on the HTTP client. If you are using .NET 4.0+ then you could increase the value on the Timeout property of the StardogConnector class. If you are using .NET Core then I'm afraid you are out of luck because the .NET Core 1.x version of HttpWebRequest does not support setting a timeout :-(

**Comment by kal** [comment]
I'm going to close this ticket. The issue with the Timeout value is to be addressed in the 2.1 milestone by #175
