### ISSUE TITLE
ORDER BY RAND can raise error in comparer

### ISSUE THREAD

**Issue by kal** [dotnetrdf/dotnetrdf#344]
Happens occassionally in the unit tests (but not consistently).

System.ArgumentException : Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Collections.Generic.ComparisonComparer`1[System.Int32]'.

at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VDS.RDF.Query.Algebra.BaseMultiset.Sort(IComparer`1 comparer) in C:\projects\dotnetrdf\Libraries\dotNetRDF\Query\Algebra\BaseMultiset.cs:line 814
   at VDS.RDF.Query.Algebra.OrderBy.Evaluate(SparqlEvaluationContext context) in C:\projects\dotnetrdf\Libraries\dotNetRDF\Query\Algebra\OrderBy.cs:line 70
   at VDS.RDF.Query.Algebra.Select.Evaluate(SparqlEvaluationContext context) in C:\projects\dotnetrdf\Libraries\dotNetRDF\Query\Algebra\Select.cs:line 85
   at VDS.RDF.Query.LeviathanQueryProcessor.ProcessQuery(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, SparqlQuery query) in C:\projects\dotnetrdf\Libraries\dotNetRDF\Query\LeviathanQueryProcessor.cs:line 174
   at VDS.RDF.Query.LeviathanQueryProcessor.ProcessQuery(SparqlQuery query) in C:\projects\dotnetrdf\Libraries\dotNetRDF\Query\LeviathanQueryProcessor.cs:line 116
   at VDS.RDF.GraphExtensions.ExecuteQuery(IGraph g, String sparqlQuery) in C:\projects\dotnetrdf\Libraries\dotNetRDF\Core\Extensions.cs:line 812
   at VDS.RDF.Query.SparqlNewFunctions.SparqlOrderByNonDeterministic() in C:\projects\dotnetrdf\Testing\unittest\Query\SparqlNewFunctions.cs:line 129

Line numbers are from commit 5a5acd06

**Comment by kal** [comment]
Looking at the code, the problem seems to be that RAND() is evaluated in the Comparer that is implemented in `OrderByExpression`, so it will potentially return a different value for the same pair of operands.  One possible solution might be to have that implementation maintain a cache of the expression values keyed on the ID of the set, using the cached value if it is present so that we can guarantee that the expression is only evaluated once for each set (which might also be a little bit of a performance boost for other expressions)
