### ISSUE TITLE
Collection modification error while doing Graph.Clear()

### ISSUE THREAD

**Issue by atodkar** [dotnetrdf/dotnetrdf#442]
In a single thread while we are trying to clear all triples from the graph, I am getting collection modification error as below-

Tried using ThreadSafeGraph as well but looks like the Clear method is only implemented in BaseGraph where its not thread safe. 

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VDS.RDF.BaseGraph.Clear()
  
```

**Comment by atodkar** [comment]
I see the code below from **BaseGraph.Clear** is problematic-

```
this.Retract((IEnumerable<Triple>) this.Triples.ToList<Triple>());
```

**Comment by kal** [comment]
I cannot reproduce this error. I note that the code you show for BaseGraph.Clear() is not the code on the current main branch or on the release/3.0.0 branch. The actual code as written is:

```
Retract(Triples.ToList());
```

This code does not cast the IList returned by Triples.ToList() to an IEnumerable, which I think is the underlying problem with the code you showed. I'm not sure where that code you show has come from - is it possible that someone has modified your local copy/fork of the source?
