### ISSUE TITLE
JSON-LD Framing issue with @id value that contains an encoded uri

### ISSUE THREAD

**Issue by lambdakris** [dotnetrdf/dotnetrdf#513]
Hi, I am trying to frame a graph with the use of an @id value that contains another uri in the final segment which  was encoded using the [ENCODE_FOR_URI sparql function](https://www.w3.org/TR/sparql11-query/#func-encode).

The graph looks like so...
```
@base <http://localhost:8080/>.

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix owl: <http://www.w3.org/2002/07/owl#>.
@prefix hydra: <http://www.w3.org/ns/hydra/core#>.
@prefix ex: <http://example.org/vocab#>.

<http://localhost:8080/outline/http%3A%2F%2Flocalhost%3A8080%2Fknowledge-graph%2Fengine_01> 
    a hydra:Resource, ex:Engine;
    ex:id "engine_01".
```

And the json-ld frame looks like so...
```
{
  "@context": {
    "ex": "http://example.org/vocab#"
  },
  "@id": "http://localhost:8080/outline/http%3A%2F%2Flocalhost%3A8080%2Fknowledge-graph%2Fengine_01"
}
```

Unfortunately I am receiving the following exception
```
...
VDS.RDF.JsonLd.JsonLdProcessorException: Invalid frame. The value of the @id property must be either an array containing a single empty map; an IRI string or an array of IRI strings.
         at VDS.RDF.JsonLd.Processors.FramingProcessor.ValidateFrame(JToken value)
         at VDS.RDF.JsonLd.Processors.FramingProcessor.ProcessFrame(FramingState state, List`1 subjects, JToken frameObjectOrArray, JToken parent, String activeProperty, Boolean ordered, Stack`1 idStack, JsonLdProcessingMode processingMode)
         at VDS.RDF.JsonLd.JsonLdProcessor.Frame(JToken input, JToken frame)
...
```

I guess my question is whether there is any way to make this work or if I have to find a way to obfuscate the uri within in the final segment in such a way that the json-ld framing processor doesn't trip up?

**Comment by lambdakris** [comment]
To get an idea of whether this was a general JSON-LD limitation or might be more specific to the DotNetRDF JSON-LD Processor I tried the framing on the [JSON-LD Playground with this example](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%5B%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fvocab%23Engine%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Flocalhost%3A8080%2Foutline%2Fhttp%253A%252F%252Flocalhost%253A8080%252Fknowledge-graph%252Fengine_01%22%2C%22%40type%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2Fns%2Fhydra%2Fcore%23Resource%22%2C%22http%3A%2F%2Fexample.org%2Fvocab%23Engine%22%5D%2C%22http%3A%2F%2Fexample.org%2Fvocab%23id%22%3A%5B%7B%22%40value%22%3A%22engine_01%22%7D%5D%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fhydra%2Fcore%23Resource%22%7D%5D&frame=%7B%22%40context%22%3A%7B%22ex%22%3A%22http%3A%2F%2Fexample.org%2Fvocab%23%22%7D%2C%22%40id%22%3A%22http%3A%2F%2Flocalhost%3A8080%2Foutline%2Fhttp%253A%252F%252Flocalhost%253A8080%252Fknowledge-graph%252Fengine_01%22%7D)
