### ISSUE TITLE
Fuseki Connector: Throws unexpected Exception after calling ListGraphNames

### ISSUE THREAD

**Issue by BoolPurist** [dotnetrdf/dotnetrdf#520]
# What is the problem ?
After connecting to a Jena Fuseki Server endpoint for the Graph Store Protocol (data) ,  I call a method called ListGraphNames on an object of type FusekiConnector. It then throws an exception with the following line in the stack trace "VDS.RDF.Parsing.RdfParseException: Cannot resolve a Relative URI Reference since there is no in-scope Base URI!". 
That seems odd to me. This method does not take any arguments.

## How to reproduce ?
This following code leads to the unexpected thrown exception.

```csharp
var fuseki = new FusekiConnector("<url to graph store protocol something like .../data>");
foreach (var name in fuseki.ListGraphNames())
{
    Console.WriteLine($"{name}");
}
```

## What I expected

No exception is thrown and either no name is displayed or all the names of the named graphs, stored on Jena Fuseki server, are shown.

### Used dotnetrdf version

I use dotnetrdf as a Nuget package  with the version "3.0.0-rc0004".

### Jena Fuseki Server Setup.

I start the standalone Jena Fuseki server of version "4.6.1" with the following command
```bash
 fuseki-server  --update --mem  /test
``` 
on  loacalhost.

[Link to binary](https://jena.apache.org/download/index.cgi) for the Jena Fuseki-Server.

## Remark

The FusekiConnector returns true for the Property "ListGraphsSupported" and "IsReady". In in my view, the connection is not the problem.

## Output of thrown exception
```text
Unhandled exception. VDS.RDF.Storage.RdfStorageException: An unexpected error occurred while querying the Store. See inner exception for further details
 ---> VDS.RDF.Parsing.RdfParseException: Cannot resolve a Relative URI Reference since there is no in-scope Base URI!
   at VDS.RDF.Tools.ResolveUri(String uriref, String baseUri, IUriFactory uriFactory)
   at VDS.RDF.Parsing.RdfAParserBase`4.ProcessElement(RdfAParserContext`1 context, RdfAEvaluationContext evalContext, TElement currElement)
   at VDS.RDF.Parsing.RdfAParserBase`4.ProcessElement(RdfAParserContext`1 context, RdfAEvaluationContext evalContext, TElement currElement)
   at VDS.RDF.Parsing.RdfAParserBase`4.ProcessElement(RdfAParserContext`1 context, RdfAEvaluationContext evalContext, TElement currElement)
   at VDS.RDF.Parsing.RdfAParserBase`4.ProcessElement(RdfAParserContext`1 context, RdfAEvaluationContext evalContext, TElement currElement)
   at VDS.RDF.Parsing.RdfAParser.ProcessDocument(RdfAParserContext`1 context, RdfAEvaluationContext evalContext)
   at VDS.RDF.Parsing.RdfAParserBase`4.Parse(RdfAParserContext`1 context)
   at VDS.RDF.Parsing.RdfAParserBase`4.Load(IRdfHandler handler, TextReader input, IUriFactory uriFactory)
   at VDS.RDF.Parsing.RdfAParserBase`4.Load(IRdfHandler handler, StreamReader input)
   at VDS.RDF.Storage.FusekiConnector.Query(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, String sparqlQuery)
   --- End of inner exception stack trace ---
   at VDS.RDF.Storage.FusekiConnector.Query(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, String sparqlQuery)
   at VDS.RDF.Storage.FusekiConnector.Query(String sparqlQuery)
   at VDS.RDF.Storage.FusekiConnector.ListGraphNames()
   at Program.<Main>$(String[] args) in /home/nice_graphic/RiderProjects/GraphConsole/GraphConsole/Program.cs:line 21
```

**Comment by kal** [comment]
I have attempted to recreate this error locally with fuseki 4.6.1 and I get no error. 

What is the result of executing the following query against the store:

```
SELECT DISTINCT ?g WHERE { GRAPH ?g { ?s ?p ?o } }
```

**Comment by kal** [comment]
Closed due to lack of activity. If you have further information to help narrow down why you are seeing this error please feel free to reopen the ticket.
