### ISSUE TITLE
Failing tests on mac

### ISSUE THREAD

**Issue by stefannikolei** [dotnetrdf/dotnetrdf#534]
I started all docker containers with the provided docker compose.

Running all tests (.NET6) resulted in this:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/873751/209716549-803ef990-c546-44cb-973d-3b4ec194c426.png">

e.g. the stack trace of AllegroGraphAsync.BaseAsyncTest.StorageAsyncQuery

```
System.Exception: [AllegroGraphConnector] LoadGraph() returned error - An unexpected error occurred while querying the Store. See inner exception for ...

System.Exception
[AllegroGraphConnector] LoadGraph() returned error - An unexpected error occurred while querying the Store. See inner exception for further details
   at VDS.RDF.Storage.BaseAsyncTests.Fail(IAsyncStorageProvider provider, String msg, Exception e) in /Users/stefannikolei/projects/github/dotnetrdf/dotnetrdf/Testing/dotNetRdf.Connectors.Tests/BaseAsyncTests.cs:line 64
   at VDS.RDF.Storage.BaseAsyncTests.TestAsyncQuery(IGraph g) in /Users/stefannikolei/projects/github/dotnetrdf/dotnetrdf/Testing/dotNetRdf.Connectors.Tests/BaseAsyncTests.cs:line 470
   at VDS.RDF.Storage.BaseAsyncTests.StorageAsyncQuery() in /Users/stefannikolei/projects/github/dotnetrdf/dotnetrdf/Testing/dotNetRdf.Connectors.Tests/BaseAsyncTests.cs:line 527

VDS.RDF.Storage.RdfStorageException
An unexpected error occurred while querying the Store. See inner exception for further details
  Exception doesn't have a stacktrace

System.FormatException
The format of value '100,text/comma-separated-values;q=0,100,text/csv;q=0,100,text/comma-separated-values;q=0,100,text/tab-separated-values;q=0,100,text/tab-separated-values;q=0,100' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at VDS.RDF.Storage.BaseSesameHttpProtocolConnector.CreateRequest(String servicePath, String accept, HttpMethod method, Dictionary`2 queryParams) in /Users/stefannikolei/projects/github/dotnetrdf/dotnetrdf/Libraries/dotNetRdf.Client/Storage/SesameHTTPProtocolConnector.cs:line 1359
   at VDS.RDF.Storage.AllegroGraphConnector.CreateRequest(String servicePath, String accept, HttpMethod method, Dictionary`2 queryParams) in /Users/stefannikolei/projects/github/dotnetrdf/dotnetrdf/Libraries/dotNetRdf.Client/Storage/AllegroGraphConnector.cs:line 333
   at VDS.RDF.Storage.BaseSesameHttpProtocolConnector.MakeQueryRequestMessage(String sparqlQuery, Boolean& isAsk, SparqlQuery& q) in /Users/stefannikolei/projects/github/dotnetrdf/dotnetrdf/Libraries/dotNetRdf.Client/Storage/SesameHTTPProtocolConnector.cs:line 1226
   at VDS.RDF.Storage.BaseSesameHttpProtocolConnector.Query(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, String sparqlQuery, AsyncStorageCallback callback, Object state) in /Users/stefannikolei/projects/github/dotnetrdf/dotnetrdf/Libraries/dotNetRdf.Client/Storage/SesameHTTPProtocolConnector.cs:line 1095
```

**Comment by kal** [comment]
Hi @stefannikolei - if you have chance to retry with the updated main branch and let me know if this is fixed on the mac that would be appreciated!
