### ISSUE TITLE
RdfParseException with Non English letters

### ISSUE THREAD

**Issue by younos1986** [dotnetrdf/dotnetrdf#572]
Hi there, I am using dotNetRdf version 3.0.0, when I want to load NQuad data into trippleStore, as below 

```
         var doc = JObject.Parse(json);
            var opts = new JsonLdOptions();
            var rdf = (RDFDataset)JsonLdProcessor.ToRDF(doc, opts);
            
            var nquadsData = RDFDatasetUtils.ToNQuads(rdf); // serialize RDF to string

            var tripleStore = new TripleStore();
            var nquadsParser = new NQuadsParser(NQuadsSyntax.Original);
            
            byte[] encodedBytes = Encoding.Default.GetBytes(nquadsDataFormatted); // Replace Default with the appropriate encoding if needed
            var encodedNquadsData = Encoding.UTF8.GetString(encodedBytes); // Replace UTF8 with the desired Unicode encoding

            
            nquadsParser.Load(tripleStore, new StringReader(encodedNquadsData));  // exception throws here
```

I get the following error for non english letters 

```
    VDS.RDF.Parsing.RdfParseException: [Line 40 Column 115] Unexpected Character (Code 37): % encountered while trying to parse Unicode Escape from Content:
"Taxe de départ Ã
The \u Escape must be followed by four Hex Digits
   at VDS.RDF.Parsing.Tokens.BaseTokeniser.HandleEscapes(TokeniserEscapeMode mode)
   at VDS.RDF.Parsing.Tokens.NTriplesTokeniser.TryGetLiteral()
   at VDS.RDF.Parsing.Tokens.NTriplesTokeniser.GetNextToken()
   at VDS.RDF.Parsing.Tokens.BufferedTokenQueue.BufferInternal()
   at VDS.RDF.Parsing.Tokens.BufferedTokenQueue.Dequeue()
   at VDS.RDF.Parsing.NQuadsParser.TryParseContext(TokenisingParserContext context)
   at VDS.RDF.Parsing.NQuadsParser.TryParseQuad(TokenisingParserContext context)
   at VDS.RDF.Parsing.NQuadsParser.Parse(TokenisingParserContext context)
   at VDS.RDF.Parsing.NQuadsParser.LoadInternal(IRdfHandler handler, TextReader input, IUriFactory uriFactory)
   at VDS.RDF.Parsing.NQuadsParser.Load(IRdfHandler handler, TextReader input, IUriFactory uriFactory)
   at VDS.RDF.Parsing.NQuadsParser.Load(ITripleStore store, TextReader input)
```

**Comment by kal** [comment]
Hi younos,

Do you have any further information on exactly what stream of characters is being read into the parser (e.g. can you show me what the content of the `encodedNquadsData` string actually is). The error indicates that there is some badly formatted unicode escape sequence in the input data, but without seeing the data I can't be sure if that is the problem or if something else is the problem.

**Comment by kal** [comment]
I'm closing this issue for now, but if you can provide more information about the input that is causing the problem, we can re-open it.
