### ISSUE TITLE
[BUG] Issue with serializing a graph containing rdf:nil in JSON-LD format

### ISSUE THREAD

**Issue by petarhristov94** [dotnetrdf/dotnetrdf#600]
When trying to serialize a graph containing the `rdf:nil` element into `JSON-LD` format using the dotnetRDF library, a `KeyNotFoundException` error is thrown.

#### Steps to Reproduce:
1. Create a graph with Turtle format containing an `rdf:nil` element, as shown in the provided code.
2. Parse this Turtle string into an `IGraph` instance.
3. Try to write the graph to a string in the `JSON-LD` format.

#### Expected Behavior:
- The graph should be successfully serialized into `JSON-LD` format without any errors.

#### Observed Behavior:
- Affected package version `3.1.0`
- The serialization process throws the following error:
```csharp
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '_:autos28' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at VDS.RDF.Writing.JsonLdWriter.IsWellFormedListNode(JObject node, String property, Dictionary`2 nodeUsagesMap)
   at VDS.RDF.Writing.JsonLdWriter.SerializeStore(ITripleStore store)
   at VDS.RDF.Writing.JsonLdWriter.Save(ITripleStore store, TextWriter output, Boolean leaveOpen)
   at VDS.RDF.Writing.BaseStoreWriter.Save(ITripleStore store, TextWriter output)
   at VDS.RDF.Writing.StringWriter.Write(ITripleStore store, IStoreWriter writer)
   at Program.WriteToString(IGraph graph)
   at Program.Main()
Command terminated by signal 6
```

#### Source code: 
```csharp
using System;
using VDS.RDF;
using VDS.RDF.Parsing;
using StringWriter = VDS.RDF.Writing.StringWriter;

public class Program
{
	public static void Main()
	{
		string turtleContent = @"
@base <https://purl.org/coscine/ap/Dataverse_Citation_Metadata/minimal/>.

@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix dcterms: <http://purl.org/dc/terms/>.
@prefix sh: <http://www.w3.org/ns/shacl#>.

_:autos28 rdf:first ""P1"";
          rdf:rest _:autos29.
_:autos29 rdf:first ""P2"";
          rdf:rest _:autos30.
_:autos30 rdf:first ""P3"";
          rdf:rest _:autos31.
_:autos31 rdf:first ""P4"";
          rdf:rest _:autos32.
_:autos32 rdf:first ""P5"";
          rdf:rest _:autos33.
_:autos33 rdf:first ""P6"";
          rdf:rest _:autos34.
_:autos34 rdf:first ""P7"";
          rdf:rest _:autos35.
_:autos35 rdf:first ""P8"";
          rdf:rest _:autos36.
_:autos36 rdf:first ""P9"";
          rdf:rest _:autos37.
_:autos37 rdf:first ""P10"";
          rdf:rest _:autos38.
_:autos38 rdf:first ""P11"";
          rdf:rest _:autos39.
_:autos39 rdf:first ""P12"";
          rdf:rest _:autos40.
_:autos40 rdf:first ""P13"";
          rdf:rest _:autos41.
_:autos41 rdf:first ""P14"";
          rdf:rest rdf:nil.
		  
<https://purl.org/coscine/ap/Dataverse_Citation_Metadata/minimal/> dcterms:created ""2023-08-04""^^xsd:date;
                                                                    dcterms:description ""Description DE""@de,
                                                                                        ""Description EN""@en;
                                                                    dcterms:license ""https://spdx.org/licenses/CC-BY-4.0.html"";
                                                                    dcterms:title ""Title DE""@de,
                                                                                  ""Title EN""@en;
                                                                    a rdfs:Class,
                                                                      sh:NodeShape;
                                                                    sh:closed false;
																	
                                                                    sh:property [].
";
		// Parse the Turtle string into an IGraph
		IGraph graph = new Graph();
		TurtleParser turtleParser = new TurtleParser();
		turtleParser.Load(graph, new System.IO.StringReader(turtleContent));
		
		// Write the graph to string as JSON LD
		Console.WriteLine(WriteToString(graph));
	}

	private static string WriteToString(IGraph graph)
	{
		var contentType = "application/ld+json";
		// JSON-LD not meant for single graph
		var tripleStore = new TripleStore();
		tripleStore.Add(graph);
		var storeWriter = MimeTypesHelper.GetStoreWriter(contentType);
		return StringWriter.Write(tripleStore, storeWriter);
	}
}
```

**Comment by kal** [comment]
Thanks for the report @petarhristov94 ! This is now fixed and I'll make a 3.1.1 release to get the updated packages onto nuget
